### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by OsirisFrik** [loverajoel/spotify-js#23]
On import lib throw error with message self is not defined

![image](https://user-images.githubusercontent.com/9331532/60401595-89e64c00-9b49-11e9-8752-fa664abcfde4.png)

**Comment by area73** [comment]
same here, working with node:
```javaScript
const { Client } = require('spotify-sdk');
```
Throws:
```bash
ReferenceError: self is not defined
    at Object.<anonymous> (/Users/.../node_modules/spotify-sdk/lib/dist.js:22:12223)

```

And If I try running with ES6  modules I got:

```bash
import { Client, UserHandler, TrackHandler, PlaylistHandler, ArtistHandler } from 'spotify-sdk';
         ^^^^^^
SyntaxError: The requested module 'spotify-sdk' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'spotify-sdk';
const { Client, UserHandler, TrackHandler, PlaylistHandler, ArtistHandler } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)

```

**Comment by ogallagher** [comment]
Same for me, too.

| key | value |
| --- | ------ |
| npm version | `9.6.4` |
| node version | `19.2.0` |
